### ISSUE TITLE
Need a roadmap

### ISSUE THREAD

**Issue by guanidene** [guanidene/syncer#1]

**Comment by AkashGanesan** [comment]
# A rough roadmap

Hi Pushpak,  I just put together a rough roadmap.  I still am not very clear as to how to achiever synching between N-machines.  Anyways, perhaps we can start with this.

## Core Functionality

### NEXT Data structure for store
-   [ ] Data structure to hold information about root directory (let’s call it store for now)
  -   [ ] Decide on what to store (necessary information)
  -   [ ] Decide on how to store efficiently (pickling)

### TODO Basic operations on store
-   [ ] Basic operations to library
  -   [ ] Update store for the following
-   [ ] Add files to store for tracking
-   [ ] Remove files from store
-   [ ] Update information about changes to files to store.

### TODO Synching between stores of same type
-   [ ] Find a good algortihm for resolving conflicts. Conflicts we have to deal with are simpler than what git handles.

## Usability
-   [ ] Abstracting operation channel
  -   [ ] Allow for said core functionality over ssh/https, etc.

**Comment by guanidene** [comment]
Closed the issue for now.
